language: python

python:
  - "3.6"

# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

# http://docs.travis-ci.com/user/customizing-the-build/#Git-Submodules
git:
  submodules: false
  
before_install:
  # https://gist.github.com/iedemam/9830045
  # - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
  #
  # https://git-scm.com/docs/git-submodule#_options:
  # --remote
  # Instead of using the superproject’s recorded SHA-1 to update the submodule,
  # use the status of the submodule’s remote-tracking (branch.<name>.remote) branch (submodule.<name>.branch).
  # --recursive
  # https://github.com/travis-ci/travis-ci/issues/4099
  - git submodule update --init --remote --recursive

# Clean and don't fail
#install:
#  - rm -rf public || exit 0
install:
  - pip install -r requirements.txt

# Build the website
script:
  - cd src
  - fab render_notebooks
  - ../binaries/hugo --theme=robust-local

# Deploy to GitHub pages
deploy:
  provider: pages
  local_dir: src/public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
